version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
   configuration: docs/conf.py

python:
  install:
  - method: pip
#   version: 3.8
##   install:
#   - method: setuptools
#     path: .
